version: '2.3'

services:
  nest_api:
    build: .
    container_name: nest_api
    restart: 'unless-stopped'
    ports:
      - 4400:4400
    env_file:
      - ./.env
    networks:
      - nest_api
  redis:
    image: redis:6.2-alpine
    container_name: nest_redis
    restart: 'unless-stopped'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - nest_api

networks:
  nest_api:
    name: nest_networks
    external: true
