version: '3.3'

services:
  metabase_db:
    container_name: metabase_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - nest_metabase
  metabase:
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=metabase_db
    image: metabase/metabase
    container_name: nest_metabase
    restart: always
    depends_on:
      - metabase_db
    networks:
      - nest_metabase
networks:
  nest_metabase:
    name: nest_networks
    external: true
